## Column Transformation in Pandas

In [1]:
import pandas as pd

Row & Column Selection

In [5]:
studentData = pd.read_csv("Subdata_pandas/student.csv")
studentData

    id firstName  lastName  age  marks   fees
0  101    Akshay    Shetty   20     85  25000
1  102    Ananya       Rao   21     92  30000
2  103     Rohit  Bhandary   19     76  28000
3  104     Nisha   D'Souza   20     88  25000
4  105   Karthik   Poojary   22     69  32000
5  106    Shreya    Shetty   19     95  30000
6  107     Rohan      Naik   21     72  27000
7  108   Deepika      Bhat   20     81  28000
8  109  Abhishek    Kotian   22     64  26000
9  110     Pooja       Rai   19     90  30000

In [ ]:
#Select a specific column
studentData[['firstName','marks']]
#Select on name select row
studentData.loc[studentData.firstName=="Rohit"]
studentData.loc[studentData.id==103]
studentData.loc[studentData.marks>=90]
studentData.loc[:2]
studentData.iloc[:5]
studentData.iloc[:5,1:4]
studentData[['firstName','age','fees']]

  firstName   fees
0    Akshay  25000
1    Ananya  30000
2     Rohit  28000
3     Nisha  25000
4   Karthik  32000
5    Shreya  30000
6     Rohan  27000
7   Deepika  28000
8  Abhishek  26000
9     Pooja  30000